export enum UseCases {

    ON_SIGNIN_USER = 100,
    ON_VERIFICATION_USER = 200,
    ON_ACTIVATE_DEVICE = 300,
    ON_ACTIVATE_ACCOUNT = 400,
    ON_GETTING_DEVICES = 500,
    ON_SAVE_VEHICLE = 600,
    ON_DELETE_VEHICLE = 700,
    ON_DELETE_GROUP = 700

}